//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autentification.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaysEntities : DbContext
    {
        public PaysEntities()
            : base("name=PaysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Localite> Localite { get; set; }
        public virtual DbSet<Pays> Pays { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
