//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activ.Pointis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsConnexion
    {
        public long ID { get; set; }
        public string telephone_imei { get; set; }
        public System.DateTime date_connexion { get; set; }
        public string numero_telephone { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string ApplicationID { get; set; }
    }
}
