//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activ.Pointis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public long ID { get; set; }
        public string NotifcationBody { get; set; }
        public string SMSNumber { get; set; }
        public string SMSSender { get; set; }
        public string MAILFrom { get; set; }
        public string MAILTo { get; set; }
        public string MAILSubject { get; set; }
        public string NotifcationNature { get; set; }
        public byte NotificationStatus { get; set; }
    }
}
