//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activ.Pointis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Employes
    {
        public string Nom { get; set; }
        public long EmployeID { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Sexe { get; set; }
        public long SocieteID { get; set; }
        public string Titre { get; set; }
        public string Matricule { get; set; }
        public Nullable<long> EquipeID { get; set; }
        public string EquipeNom { get; set; }
        public string EquipeDebutService { get; set; }
        public string EquipeFinService { get; set; }
        public string SocieteRaisonSociale { get; set; }
        public string SocieteRCCM { get; set; }
        public string SocieteEmail { get; set; }
        public string SocieteTelephone { get; set; }
    }
}
